name: Test Clean Install

on:
  push:
    paths:
      - "**/*.go"
    branches:
      - "!v*"

  workflow_dispatch:

jobs:
  Clean-Build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ "1.21", "1.22", "1.23" ]

    steps:
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: |
          go version

      - name: Build Murex
        run: |
          GOBIN="$(pwd)" go install -v github.com/lmorg/murex@${{ github.ref_name }}

      - name: Display Murex version
        run: |
          ./murex --version
